<template>
    <div id="mainpage">
        <div style="padding-top: 4rem; padding-bottom: 2rem;">
            <div class="maintitle">
                TW2 projects<br />
                <span style="font-size: x-small;">TW2 aka The Wingate 2940 aka Chien-Rouge aka RedDog,csa aka Chevalier Suprême de l'Apocalypse</span>
            </div>
        </div>
        <div>    
            <div v-for="project in projects">
                <TProject :project="project" :key="project._id" />
            </div>
        </div>
        <div style="padding-top: 2rem; padding-bottom: 4rem;">
            <div class="maintitle">
                <NuxtLink to="https://github.com/TW2">TW2 GitHub page</NuxtLink>
            </div>
        </div>
    </div>    
</template>

<style lang="css">
#mainpage {
    overflow-y: auto;
}
.maintitle {
    width: 100%;
    text-align: center;
    font-family: Open Sans, sans-serif;
    font-size: xx-large;
    font-weight: bolder;
}

a:link, a:visited {
    text-decoration: none;
    color: currentColor;
}
</style>

<script setup>
const projects = [
{
    _id: 1,
    name: 'assfxmaker',
    url: 'https://github.com/TW2/assfxmaker',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Make karaoke in ASSA format. You can also make drawing for this format. Then reuse these karaoke and drawing in your ASSA program like Aegisub or LoliSub.',
    type: 'Software',
    details: 'assfxmaker',
},
{
    _id: 2,
    name: 'AST',
    url: 'https://github.com/TW2/AST',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Translate an ASSA file with libretranslate.',
    type: 'Software',
    details: 'ast',
},
{
    _id: 3,
    name: 'Chuu',
    url: 'https://github.com/TW2/Chuu',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Edit a Visual Novel. Not ready !',
    type: 'Software',
    details: 'chuu',
},
{
    _id: 4,
    name: 'Caramel Milkshake',
    url: 'https://github.com/TW2/cmilkshake',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Compare 2 ASSA files in a side by side view and show charts.',
    type: 'Software',
    details: 'cmilkshake',
},
{
    _id: 5,
    name: 'CNMPlayer',
    url: 'https://github.com/TW2/CNMPlayer',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub, Manga',
    desc: 'Reader of CNM file (comics and manga).',
    type: 'Software',
    details: 'cnmplayer',
},
{
    _id: 6,
    name: 'CNMStudio',
    url: 'https://github.com/TW2/CNMStudio',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub, Manga',
    desc: 'Create or read a CNM file (comics and manga).',
    type: 'Software',
    details: 'cnmstudio',
},
{
    _id: 7,
    name: 'CSASS',
    url: 'https://github.com/TW2/CSASS',
	lang: 'C#',
	license: 'GNU/LGPLv3',
	people: 'Fansub',
    desc: 'Read/Write ASSA files.',
    type: 'API',
    details: 'csass',
},
{
    _id: 8,
    name: 'dotREVO',
    url: 'https://github.com/TW2/dotREVO',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Not ready !',
    type: 'Software',
    details: 'dotrevo',
},
{
    _id: 9,
    name: 'Feuille',
    url: 'https://github.com/TW2/Feuille',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'A successor for AFM (AssFxMaker).',
    type: 'Software',
    details: 'feuille',
},
{
    _id: 10,
    name: 'FontBox',
    url: 'https://github.com/TW2/FontBox',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub, others',
    desc: 'Open and write TTF/OTF fonts. Not ready !',
    type: 'API',
    details: 'fontbox',
},
{
    _id: 11,
    name: 'IVR4UCBZ',
    url: 'https://github.com/TW2/IVR4UCBZ',
	lang: 'Java',
	license: 'Creative Commons Zero v1.0 Universal',
	people: 'Fansub, Manga',
    desc: 'A viewer in vertical mode for uncrypted CBZ (big zip).',
    type: 'Software',
    details: 'ivr4ucbz',
},
{
    _id: 12,
    name: 'Karaoke-Utilities',
    url: 'https://github.com/TW2/Karaoke-Utilities',
	lang: 'Lua',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Scripts for fansubbers using Aegisub.',
    type: 'Scripts',
    details: 'karaoke-utilities',
},
{
    _id: 13,
    name: 'KGM-Swing',
    url: 'https://github.com/TW2/KGM-Swing',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Make music with this control.',
    type: 'Controls',
    details: 'kgm-swing',
},
{
    _id: 14,
    name: 'konnpetkoll',
    url: 'https://github.com/TW2/konnpetkoll',
	lang: 'Java',
	license: 'No license',
	people: 'Others',
    desc: 'Collection of controls.',
    type: 'Controls',
    details: 'konnpetkoll',
},
{
    _id: 15,
    name: 'KuroShiro',
    url: 'https://github.com/TW2/KuroShiro',
	lang: 'JS',
	license: 'GNU/GPLv3',
	people: 'Others',
    desc: 'Discord bot to download files using NodeJS.',
    type: 'Bot',
    details: 'kuroshiro',
},
{
    _id: 16,
    name: 'LoliSub',
    url: 'https://github.com/TW2/LoliSub',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'A successor of Feuille. Not ready !',
    type: 'Software',
    details: 'lolisub',
},
{
    _id: 17,
    name: 'Mirage-Team-Database',
    url: 'https://github.com/TW2/Mirage-Team-Database',
	lang: 'Java',
	license: 'MIT',
	people: 'Fansub',
    desc: 'The CP9-Team and Mirage-Team attacks of One Piece.',
    type: 'Scripts',
    details: 'mirage-team-database',
},
{
    _id: 18,
    name: 'MyAuthoring',
    url: 'https://github.com/TW2/MyAuthoring',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub, Video, BluRay',
    desc: 'Create video and menu to view Fansub files using FFMPEG on BluRay. Not ready !',
    type: 'Software',
    details: 'myauthoring',
},
{
    _id: 19,
    name: 'PlayWithRegex',
    url: 'https://github.com/TW2/PlayWithRegex',
	lang: 'Java',
	license: 'GNU/LGPLv2.1',
	people: 'Others',
    desc: 'Create and test regular expressions.',
    type: 'Software',
    details: 'playwithregex',
},
{
    _id: 20,
    name: 'PointsAndCurves',
    url: 'https://github.com/TW2/PointsAndCurves',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Drawing mode of AFM/Feuille in a standalone app.',
    type: 'Software',
    details: 'pointsandcurves',
},
{
    _id: 21,
    name: 'Progressive',
    url: 'https://github.com/TW2/Progressive',
	lang: 'Java',
	license: 'Creative Commons Zero v1.0 Universal',
	people: 'Video',
    desc: 'Record video.',
    type: 'Software',
    details: 'progressive',
},
{
    _id: 22,
    name: 'ReBuilder',
    url: 'https://github.com/TW2/ReBuilder',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Server',
    desc: 'ReUI Builder. Not ready !',
    type: 'Software',
    details: 'rebuilder',
},
{
    _id: 23,
    name: 'RedPlanetX',
    url: 'https://github.com/TW2/RedPlanetX',
	lang: 'C#',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Another video tool. Not ready !',
    type: 'Software',
    details: 'redplanetx',
},
{
    _id: 24,
    name: 'SakuraNetworks',
    url: 'https://github.com/TW2/SakuraNetworks',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Server, NAS, Docker',
    desc: 'Not ready !',
    type: 'Software',
    details: 'sakuranetworks',
},
{
    _id: 25,
    name: 'signal',
    url: 'https://github.com/TW2/signal',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Video',
    desc: 'Collection of controls based on FFMPEG audio/video.',
    type: 'Controls',
    details: 'signal',
},
{
    _id: 26,
    name: 'SingleCueSplitter',
    url: 'https://github.com/TW2/SingleCueSplitter',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Audio',
    desc: 'A FFMPEG converter and auto tagger for your CUE files.',
    type: 'Software',
    details: 'singlecuesplitter',
},
{
    _id: 27,
    name: 'SoCute',
    url: 'https://github.com/TW2/SoCute',
	lang: 'C#',
	license: 'GNU/GPLv3',
	people: 'Fansub, Video',
    desc: 'SUP to ASS converter.',
    type: 'Software',
    details: 'socute',
},
{
    _id: 28,
    name: 'SSASS',
    url: 'https://github.com/TW2/SSASS',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'Renderer for ASSA format. Not ready !',
    type: 'API',
    details: 'ssass',
},
{
    _id: 29,
    name: 'TimeLibrary',
    url: 'https://github.com/TW2/TimeLibrary',
	lang: 'Java',
	license: 'GNU/GPLv3',
	people: 'Others',
    desc: 'Old !',
    type: 'API',
    details: 'timelibrary',
},
{
    _id: 30,
    name: 'WebVTT-to-ASS',
    url: 'https://github.com/TW2/WebVTT-to-ASS',
	lang: 'C#',
	license: 'GNU/GPLv3',
	people: 'Fansub',
    desc: 'WebVTT to ASS converter.',
    type: 'Software',
    details: 'webvtt-to-ass',
},
];
</script>